# Generated by Django 4.0.1 on 2022-05-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_task_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_created',
            new_name='created',
        ),
    ]
