# Generated by Django 4.0.1 on 2022-05-10 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_task_invoice_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Deadline: Must be Formated> Y-D-M Hr:Min'),
        ),
    ]
