# Generated by Django 4.0.1 on 2022-05-10 16:29

from django.db import migrations, models
import email.utils


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='font_family',
            field=models.CharField(blank=True, choices=[('Times New Roman', 'Times New Roman'), ('Arial', 'Arial'), ('Calibri', 'Calibri')], default='Select', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='line_spacing',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('1.5 lines', '1.5 lines'), ('Doudle', 'Double')], default='Select', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(blank=True, default=email.utils.localtime, null=True, verbose_name='Deadline: Must be Formated> Y-D-M Hr:Min:Sec '),
        ),
    ]
